### ISSUE TITLE
Doesn't work on Nativescript 7

### ISSUE THREAD

**Issue by ghost** [triniwiz/nativescript-stripe#127]
The plugin doesn't work with Nativescript 7. Would you please provide an updated version?

**Comment by careeat** [comment]
I confirm. The plugin does not work with ns7. Is there another alternative to manage payments or are you planning to update

**Comment by careeat** [comment]
regards :D

**Comment by triniwiz** [comment]
New update but I’m slowly working my way up the queue 


Sent from Yahoo Mail for iPhone


On Friday, November 27, 2020, 3:32 PM, careeat <notifications@github.com> wrote:




regards :D

**Comment by pralakk16** [comment]
Hi @triniwiz I was wondering how far you have gotten into adding support for NS7. But I have two problems: my current project is running Angular 11 with NS7. So I'm wondering if the problem is that Ivy with Angualar 11 is not working with the nativescript-stripe plugin or that Nativescript 7 is not working. Please let me know. Thanks

**Comment by triniwiz** [comment]
Support for v7 is available @ https://github.com/triniwiz/nativescript-plugins

**Comment by ghost** [comment]
I just tried out the updated plugin using native script 7.0.11 but my compiler is throwing the following error “Property ‘card’ does not exist on type CreditCardView”.

My import statement is:
import { CreditCardView, Card, Stripe, Token } from "@triniwiz/nativescript-stripe";


I’m implementing my app in pure Typescript and these are the two lines from my app which works using Nativescript 6.8 using the previous version of the plugin.

Here’s my code. The error is showing up on the ccView.card statement.

 const ccView: CreditCardView = page.getViewById("card") as CreditCardView;
 stripe.createCardToken(ccView.card, (error, token) => {

Am I doing something wrong?
 Nachman Ross

On Dec 5, 2020, at 10:55 PM, Osei Fortune <notifications@github.com <mailto:notifications@github.com> > wrote:


Support for v7 is available @ https://github.com/triniwiz/nativescript-plugins

**Comment by ghost** [comment]
I just realized that I should change my call to stripe.createCardToken(ccView.cardParams, (error, token) => {

Thank you.

On Dec 6, 2020, at 9:39 AM, Nachman Ross <nross@benalterdevelopment.com <mailto:nross@benalterdevelopment.com> > wrote:

I just tried out the updated plugin using native script 7.0.11 but my compiler is throwing the following error “Property ‘card’ does not exist on type CreditCardView”.

My import statement is:
import { CreditCardView, Card, Stripe, Token } from "@triniwiz/nativescript-stripe";


I’m implementing my app in pure Typescript and these are the two lines from my app which works using Nativescript 6.8 using the previous version of the plugin.

Here’s my code. The error is showing up on the ccView.card statement.

 const ccView: CreditCardView = page.getViewById("card") as CreditCardView;
 stripe.createCardToken(ccView.card, (error, token) => {

Am I doing something wrong?
 Nachman Ross

On Dec 5, 2020, at 10:55 PM, Osei Fortune <notifications@github.com <mailto:notifications@github.com> > wrote:


Support for v7 is available @ https://github.com/triniwiz/nativescript-plugins
